name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: /usr/bin:${{ github.workspace }}/.local/bin:${{ github.workspace }}/android-sdk/build-tools/33.0.2:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git libssl-dev libltdl-dev libtool-bin libtool automake autoconf m4
        pip install --upgrade pip setuptools wheel buildozer virtualenv
        pip install --upgrade Cython==0.29.33
        pip install kivy-garden
         
        sudo apt-get update
        sudo apt-get install -y libtool
        sudo ln -s /usr/share/aclocal /usr/local/share/aclocal || true

        sudo apt update
        sudo apt install -y libtool libtool-bin

        libtool --version

    - name: Install Kivy Garden mapview
      run: python -m garden install mapview


    - name: Set up Android SDK
      run: |
        mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools"
        rm sdk.zip

        mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools" "${ANDROID_SDK_ROOT}/cmdline-tools/latest"

        export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:$PATH"
        export ANDROID_NDK_HOME=/home/runner/android-sdk/ndk/25.2.9519653

        # Clean build-tools and NDK directories
         rm -rf "$ANDROID_SDK_ROOT/build-tools/33.0.2"
         rm -rf "$ANDROID_SDK_ROOT/ndk/23.1.7779620"  # clean old NDK if exists
         rm -rf /home/runner/android-sdk/ndk/23.1.7779620

         # Remove existing NDKs to avoid conflicts
         rm -rf "${ANDROID_SDK_ROOT}/ndk" || true

        yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses
        "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653" \
          "cmdline-tools;latest"

    - name: Export Android environment variables
      run: |
        echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "PATH=${ANDROID_SDK_ROOT}/build-tools/33.0.2:${ANDROID_SDK_ROOT}/platform-tools:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

 
    - name: Clean Buildozer Cache
      run: |
       rm -rf .buildozer
       rm -rf .cache
       rm -rf ~/.buildozer

    - name: Clear pip cache
      run: |
       pip cache purge
  
    - name: Patch googletest Python2 print issue in NDK
      run: |
        GTEST_FILE="${ANDROID_SDK_ROOT}/ndk/25.2.9519653/sources/third_party/googletest/scripts/gen_gtest_pred_impl.py"
        if [ -f "$GTEST_FILE" ]; then
          echo "✅ Patching $GTEST_FILE to use Python 3 syntax..."
          sed -i "s/^print\s\+\(.*\)$/print(\1)/" "$GTEST_FILE"
          echo "✅ Patch complete. Verifying change:"
          grep -n 'print' "$GTEST_FILE" | head -n 5
        else
          echo "❌ File not found: $GTEST_FILE"
          exit 1
        fi


    - name: Build APK
      run: |
        echo "🔁 Re-running Buildozer to generate APK..."
        buildozer android debug --requirement-cleanup --force-build


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: .buildozer/android/platform/build/dists/*/bin/*.apk

