name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git libssl-dev
        pip install --upgrade pip setuptools wheel cython buildozer
        
    - name: Check git version
      run: git --version     

    - name: Set up Android SDK
      run: |
       export ANDROID_SDK_ROOT="$HOME/android-sdk"
    
       mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
       cd "$ANDROID_SDK_ROOT/cmdline-tools"
    
       curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
       unzip sdk.zip -d temp
       rm sdk.zip
    
       mv temp/cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
       rm -rf temp
    
       yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses
       "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
       "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"

    - name: Ensure git installed
      run: sudo apt-get install -y git


    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk
        PATH: /usr/bin:${{ env.HOME }}/.local/bin:${{ env.HOME }}/android-sdk/platform-tools:${{ env.HOME }}/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: kivyapp/bin/*.apk
