name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # DO NOT set $HOME in env this way - variables won't expand properly
    # Instead, set in shell scripts.
    env:
      ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk
      PATH: /usr/bin:${{ env.HOME }}/.local/bin:${{ env.HOME }}/android-sdk/build-tools/33.0.2:${{ env.HOME }}/android-sdk/platform-tools:${{ env.HOME }}/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git libssl-dev
        pip install --upgrade pip setuptools wheel cython buildozer virtualenv

    - name: Set up Android SDK
      run: |
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
        rm sdk.zip
  
        # Move cmdline-tools folder to 'latest' directory as expected
        mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
  
        # Use sdkmanager from the correct location
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses
  
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
          "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;23.1.7779620"

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk
        PATH: /usr/bin:${{ env.HOME }}/.local/bin:${{ env.HOME }}/android-sdk/build-tools/33.0.2:${{ env.HOME }}/android-sdk/platform-tools:${{ env.HOME }}/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        echo "Git version in PATH:"
        git --version

        echo "Building APK..."
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: ./.buildozer/android/platform/build/dists/**/bin/*.apk
